:global:
  componentName: prometheus-pushgateway
  githubUrl: https://github.com/projectsyn/component-prometheus-pushgateway
  feature_goldenTests: true

docs/antora.yml:
  name: prometheus-pushgateway
  title: Prometheus Pushgateway
