parameters:
  kapitan:
    compile:
      - input_paths:
          - prometheus-pushgateway/component/app.jsonnet
        input_type: jsonnet
        output_path: apps/
      - input_paths:
          - prometheus-pushgateway/component/main.jsonnet
        input_type: jsonnet
        output_path: prometheus-pushgateway/

